language: erlang
before_install:
  - sudo apt-get install -qq xsltproc
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
script: "./travis-tool.sh run_tests && make install && make test"
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package assertthat
services:
  - elasticsearch
  - rabbitmq
otp_release:
#  - R16B02
#  - R16B01
  - R16B
  
  
